apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-kemkas-hu
  namespace: kemkas
  annotations:
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: letsencrypt-app-kemkas-hu
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kemkas-service
            port:
              number: 8080
    host: app.kemkas.hu
  tls:
  - hosts:
    - kemkas.hu
    - app.kemkas.hu
    secretName: letsencrypt-app-kemkas-hu
