apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kemkas-external-secrets
  namespace: kemkas
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: kemkas-secret-store
    kind: SecretStore
  target:
    name: kemkas-envs
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kemkas-app
