apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kemkas-secret-store
  namespace: kemkas
spec:
  provider:
    onepassword:
      connectHost: https://1password-connect.dev.kemkas.hu
      vaults:
        kemkas: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token